### ISSUE TITLE
[SECURITY] - Please rebuild image

### ISSUE THREAD

**Issue by ezramorris** [UKHomeOffice/docker-nginx-proxy#133]
Hi,

There are a number of secruity vulnerabilities identified on the [Quay security scanner](https://quay.io/repository/ukhomeofficedigital/nginx-proxy/manifest/sha256:c10129e3b6d156167b1c17d6864b17262f8d8dd5020dec146fafc61ac2631312?tab=vulnerabilities).

Most of these seem to be with packages installed using yum, so a rebuild and push with the existing files should resolve them.

Many thanks.

**Comment by jcbgrub** [comment]
This has been addressed with the latest tag 4.0.0, which is passing the [Quay security scanner](https://quay.io/repository/ukhomeofficedigital/nginx-proxy/manifest/sha256:01e32755d90287edd01883e8e195f9619b17305f205bf543682dc049701e5cdc?tab=vulnerabilities)
