### ISSUE TITLE
create a feature for rate limiting on IP 

### ISSUE THREAD

**Issue by jon-shanks** [UKHomeOffice/docker-nginx-proxy#36]
Offer an option so that if someone wants to set a rate limit for requests i.e. IP(x) can make y request per s .

**Comment by lewismarshall** [comment]
I would simply use https://github.com/UKHomeOffice/docker-nginx-proxy#arbitrary-config

e.g. use ADD_NGINX_SERVER_CFG or ADD_NGINX_LOCATION_CFG
