### ISSUE TITLE
Add security header restrictions 

### ISSUE THREAD

**Issue by jon-shanks** [UKHomeOffice/docker-nginx-proxy#42]
We should add some default security restrictions on headers and assets

add_header Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'" always;

add_header Strict-Transport-Security "max-age=31536000; includeSubdomains" always;

add_header X-Frame-Options "SAMEORIGIN" always;

add_header X-Xss-Protection "1; mode=block" always;

add_header X-Content-Type-Options "nosniff" always;

**Comment by jon-shanks** [comment]
We will need to test these on different browsers

**Comment by JoeChapman** [comment]
We are implementing this in HOF: https://content-security-policy.com/

**Comment by JoeChapman** [comment]
https://github.com/UKHomeOffice/docker-nginx-proxy/pull/77
