### ISSUE TITLE
Do we need to run as root?

### ISSUE THREAD

**Issue by daniel-ac-martin** [UKHomeOffice/docker-nginx-proxy#43]
@timgent noticed that this container will run as root. Presumably, this is so we can use ports 80 and 443.

But do we need to do this? Could we not instead open a higher port (should we even open two?) and have the mapping done at a higher level?

Do we care about this?

**Comment by lewismarshall** [comment]
nginx starts as root but runs as nginx!

**Comment by daniel-ac-martin** [comment]
Ah, just like apache would.
